In [2]:
import numpy as np 
from itertools import combinations, permutations



In [3]:
model_forecasts = np.loadtxt('model_forecasts.txt', delimiter=',')

In [6]:
print(model_forecasts)

[[ 0.   -2.3  -4.59 -4.83  3.13  4.13  1.07  2.29  0.44  4.35]
 [ 2.3   0.    3.57 -4.66  2.3  -3.24  3.63  0.41 -2.   -0.77]
 [ 4.59 -3.57  0.    1.47  1.15 -1.16  4.97  4.81  1.86  1.5 ]
 [ 4.83  4.66 -1.47  0.    0.25 -1.9  -0.14  3.89  4.34 -1.42]
 [-3.13 -2.3  -1.15 -0.25  0.    3.9  -2.73  1.23 -4.16  3.33]
 [-4.13  3.24  1.16  1.9  -3.9   0.   -0.5   2.96 -2.69 -4.48]
 [-1.07 -3.63 -4.97  0.14  2.73  0.5   0.    4.42 -1.35 -3.95]
 [-2.29 -0.41 -4.81 -3.89 -1.23 -2.96 -4.42  0.    4.49 -0.4 ]
 [-0.44  2.   -1.86 -4.34  4.16  2.69  1.35 -4.49  0.    2.29]
 [-4.35  0.77 -1.5   1.42 -3.33  4.48  3.95  0.4  -2.29  0.  ]]


In [5]:
np.fill_diagonal(model_forecasts, 0)

In [8]:
def find_optimal_pairing(forecasts):
    
    n_teams = forecasts.shape[0]
    teams = list(range(n_teams))
    
    min_sum_squared_diff = float('inf')
    best_pairing = None
    
    print("Searching for optimal pairing...")
    for group1 in combinations(teams, 5):
        group2 = tuple(t for t in teams if t not in group1)
                for perm2 in permutations(group2):
            sum_squared_diff = 0
            for i in range(5):
                diff = forecasts[group1[i], perm2[i]]
                sum_squared_diff += diff ** 2
            
            if sum_squared_diff < min_sum_squared_diff:
                min_sum_squared_diff = sum_squared_diff
                best_pairing = np.array([list(group1), list(perm2)])
    
    return best_pairing, min_sum_squared_diff

optimal_pairing, min_score = find_optimal_pairing(model_forecasts)

print(f"\nOptimal pairing found:")
print(optimal_pairing)

IndentationError: unindent does not match any outer indentation level (<string>, line 13)

In [9]:
def find_optimal_pairing(forecasts):
    
    n_teams = forecasts.shape[0]
    teams = list(range(n_teams))
    
    min_sum_squared_diff = float('inf')
    best_pairing = None
    
    print("Searching for optimal pairing...")
    for group1 in combinations(teams, 5):
        group2 = tuple(t for t in teams if t not in group1)
        for perm2 in permutations(group2):
            sum_squared_diff = 0
            for i in range(5):
                diff = forecasts[group1[i], perm2[i]]
                sum_squared_diff += diff ** 2
            
            if sum_squared_diff < min_sum_squared_diff:
                min_sum_squared_diff = sum_squared_diff
                best_pairing = np.array([list(group1), list(perm2)])
    
    return best_pairing, min_sum_squared_diff

optimal_pairing, min_score = find_optimal_pairing(model_forecasts)

print(f"\nOptimal pairing found:")
print(optimal_pairing)

Searching for optimal pairing...

Optimal pairing found:
[[0 1 2 3 5]
 [8 7 9 4 6]]
